"""The authoring loop: plan a spec, have a model write the task, check it, revise, then gate it.

    uv run python -m fsbench.author --seed 7 [--model z-ai/glm-5.3] [--revisions 2] [--gates]

Each candidate lives in runs/authoring/<id>/ with:
- spec.json
- every prompt's metadata and token usage (log.jsonl)
- each draft (draft-N/)
- the static-check results

Model-written code never runs on the host: build_world.py runs in a throwaway container with no
network, and the seeded world boots on a compose network with no egress. Harbor gates (--gates)
run through scripts/gate_task.py.
"""

import argparse
import json
import random
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path

import yaml

from .bundle import BundleError, materialise, parse, render
from .checks import static_check
from .drift import CATALOGUE
from .llm import Client, LLMError

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs" / "authoring"
EXEMPLARS = ["ship-checkout-v2", "stop-double-charges"]
GENERATED_MARK = "Generated by build_world.py"
SANDBOX_IMAGE = "fullstack-bench/simcloud:dev"

AREAS = ["ship-to-prod (CI/deploy/promotion)", "cloud IaC and identity (simcloud.yaml stacks, policies, federation)",
         "platform delivery (services, traffic splits, rollbacks)", "data (Postgres migrations, backfills, repair)",
         "app auth (Passkeep OIDC sessions, tokens)", "payments and webhooks (Tillpoint)",
         "async processing (queues, idempotent consumers, DLQs)", "observability-driven incident response",
         "refactoring a live service without behaviour change", "secrets and credential rotation"]
DOMAINS = ["online marketplace", "B2B invoicing", "food delivery", "ticketing", "subscription SaaS billing",
           "logistics tracking", "fitness bookings", "travel itineraries", "creator payouts", "inventory for retail"]
VENDORS = {"tillpoint": "payments", "passkeep": "identity"}


def plan(seed: int) -> dict:
    rng = random.Random(seed)
    weird = yaml.safe_load((ROOT / "fsbench" / "weirdness.yaml").read_text())
    areas = rng.sample(AREAS, 3)
    implied = {"tillpoint" for a in areas if "Tillpoint" in a} | {"passkeep" for a in areas if "Passkeep" in a}
    vendors = sorted(implied | {v for v in VENDORS if rng.random() < 0.3})
    drifts = rng.sample(sorted(CATALOGUE), rng.choice([0, 1, 2])) if rng.random() < 0.5 else []
    return {"seed": seed, "primary_area": areas[0], "secondary_areas": areas[1:], "domain": rng.choice(DOMAINS),
            "weirdness": rng.choice(weird), "vendors": vendors, "drifts": drifts,
            "steps_min": 6, "layers_min": 3}


def _skill(name: str) -> str:
    return (ROOT / "skills" / name / "SKILL.md").read_text()


def _exemplar(name: str) -> str:
    task = ROOT / "tasks" / name
    text = render(task, include=("task.toml", "instruction.md", "build_world.py", "environment", "solution", "tests",
                                 "wrong_solutions"))
    # Leave out generated files (the generator itself is included) to keep the prompt small.
    files = parse(text)
    kept = {p: c for p, c in files.items() if GENERATED_MARK not in c[:200]}
    return "".join(f"=== FILE: {p} ===\n{c}" for p, c in kept.items()) + "=== END ===\n"


def system_prompt(spec: dict) -> str:
    drift_text = "\n".join(f"- {d}: the drifted docs claim \"{CATALOGUE[d].wrong}\"; truth is discoverable via "
                           f"{'; '.join(CATALOGUE[d].truth_sources)}" for d in spec["drifts"]) or "- none"
    parts = [
        (ROOT / "fsbench" / "guide.md").read_text(),
        "# Platform skill: SimCloud\n" + _skill("simcloud"),
        *[f"# Vendor skill: {v}\n" + _skill(v) for v in spec["vendors"]],
        *([_simsaas_seed_format()] if spec["vendors"] else []),
        "# Docs drift to apply in this task (list these ids in tests/drift_manifest.json as [{\"id\": ...}])\n"
        + drift_text,
        "# Exemplar task 1 (complete; generated files omitted)\n" + _exemplar(EXEMPLARS[0]),
        "# Exemplar task 2 (complete; generated files omitted)\n" + _exemplar(EXEMPLARS[1]),
    ]
    return "\n\n".join(parts)


def _simsaas_seed_format() -> str:
    """The simulator's own seed loader, so a draft can't invent a vendor schema it won't load."""
    import ast
    source = (ROOT / "simsaas" / "server.py").read_text()
    build = next(n for n in ast.parse(source).body if isinstance(n, ast.FunctionDef) and n.name == "build")
    return ("# SimSaaS seed format (environment/simcloud/simsaas.yaml)\n"
            "The vendor simulator loads simsaas.yaml with exactly this code. `identity` seeds Passkeep and "
            "`payments` seeds Tillpoint; it reads nothing else, and a seed with neither will not start. Any other "
            "vendor state the task needs belongs in SimCloud or the repo.\n\n```python\n"
            + ast.get_source_segment(source, build) + "\n```")


def task_prompt(spec: dict) -> str:
    w = spec["weirdness"]
    vend = ", ".join(f"{v} ({VENDORS[v]})" for v in spec["vendors"]) or "none (SimCloud only)"
    return (f"Write a new task.\n\n- Domain: {spec['domain']}\n- Primary area: {spec['primary_area']}\n"
            f"- Also involve: {', '.join(spec['secondary_areas'])}\n- Vendors available: {vend}\n"
            f"- Weird mechanism to make real: {w['id']}: {w['mechanism']} (signals: {', '.join(w['signals'])})\n"
            f"- At least {spec['steps_min']} dependent steps across at least {spec['layers_min']} layers.\n"
            "- It must be original: not a reskin of the exemplars.\n\n"
            "Return the complete bundle (every required file) and nothing after === END ===.")


def sandbox_build_world(task: Path, timeout: int = 180) -> str | None:
    """Run the candidate's build_world.py in a container with no network. Returns an error or None."""
    if not (task / "build_world.py").exists():
        return None
    import os
    cmd = ["docker", "run", "--rm", "--network", "none", "--memory", "1g", "--cpus", "1", "--user",
           f"{os.getuid()}:{os.getgid()}", "-v", f"{task}:/task", "-w", "/task", "--entrypoint", "python",
           SANDBOX_IMAGE, "build_world.py"]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return f"build_world.py did not finish within {timeout}s"
    if r.returncode:
        return f"build_world.py failed:\n{(r.stderr or r.stdout)[-1500:]}"
    return None


# Harbor supplies the agent's image; the boot never starts it but compose needs one to load the project.
BOOT_OVERRIDE = f"services:\n  main:\n    image: {SANDBOX_IMAGE}\nnetworks:\n  default:\n    internal: true\n"


def sandbox_boot_world(task: Path, timeout: int = 300) -> str | None:
    """Boot the candidate's SimCloud world on a network with no egress. Returns an error or None.

    A seed whose services never pass readiness makes every trial an infrastructure error, so the
    author sees SimCloud's own error and the tail of each service's log, the way an operator would.
    """
    env = task / "environment"
    compose = env / "docker-compose.yaml"
    if not compose.exists():
        return None
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        override = Path(tmp) / "no-egress.yaml"
        override.write_text(BOOT_OVERRIDE)
        base = ["docker", "compose", "-p", f"boot-{uuid.uuid4().hex[:10]}", "--project-directory", str(env),
                "-f", str(compose), "-f", str(override)]
        try:
            up = subprocess.run([*base, "up", "--build", "--detach", "--wait", "--wait-timeout", str(timeout),
                                 "simcloud"], capture_output=True, text=True, timeout=timeout + 600)
            if up.returncode == 0:
                return None
            logs = subprocess.run([*base, "logs", "--no-color", "--tail", "15"],
                                  capture_output=True, text=True, timeout=60).stdout
            subprocess.run([*base, "cp", "simcloud:/var/lib/simcloud/logs", f"{tmp}/logs"], capture_output=True,
                           timeout=60)
            services = "".join(f"\n--- {f.relative_to(Path(tmp) / 'logs')} (last lines)\n"
                               + "\n".join(f.read_text(errors="replace").splitlines()[-4:])[-800:]
                               for f in sorted((Path(tmp) / "logs").rglob("*.log")))
            return f"the SimCloud world did not boot:\n{(logs or up.stderr)[-1500:]}{services[-3000:]}"
        except subprocess.TimeoutExpired:
            return f"the SimCloud world did not boot within {timeout}s"
        finally:
            subprocess.run([*base, "down", "--volumes", "--remove-orphans", "--rmi", "local"], capture_output=True,
                           timeout=300)


def build_skills(task: Path) -> None:
    sys.path.insert(0, str(ROOT / "scripts"))
    import build_task_skills
    build_task_skills.build(task)


class Ledger:
    def __init__(self, path: Path):
        self.path = path

    def write(self, **rec) -> None:
        with self.path.open("a") as f:
            f.write(json.dumps({"ts": round(time.time(), 1), **rec}) + "\n")


def run(seed: int, model: str, revisions: int, gates: bool, cand_id: str | None = None) -> dict:
    cand_id = cand_id or f"c{seed}-{uuid.uuid4().hex[:6]}"
    base = RUNS / cand_id
    base.mkdir(parents=True, exist_ok=True)
    ledger = Ledger(base / "log.jsonl")
    spec = plan(seed)
    (base / "spec.json").write_text(json.dumps(spec, indent=2))
    client = Client()
    sysmsg = system_prompt(spec)
    messages = [{"role": "system", "content": sysmsg}, {"role": "user", "content": task_prompt(spec)}]
    result = {"candidate": cand_id, "spec": spec, "status": "failed_static"}
    for attempt in range(revisions + 1):
        try:
            reply = client.chat(model, messages, max_tokens=48000, temperature=0.6)
        except LLMError as e:
            # Infrastructure, not a quality verdict on the task: record it and stop this candidate.
            ledger.write(stage="author", attempt=attempt, model=model, outcome="llm_error", error=str(e)[:500])
            result.update(status="llm_error", error=str(e)[:500])
            break
        ledger.write(stage="author", attempt=attempt, model=model, prompt_tokens=reply.prompt_tokens,
                     completion_tokens=reply.completion_tokens, seconds=reply.seconds, finish=reply.finish_reason)
        draft = base / f"draft-{attempt}"
        if draft.exists():
            shutil.rmtree(draft)
        try:
            files = parse(reply.text)
            materialise(files, draft)
            errors = []
        except BundleError as e:
            errors = [f"the reply is not a valid bundle: {e}"]
        if not errors:
            err = sandbox_build_world(draft)
            errors = [err] if err else []
        if not errors:
            try:
                build_skills(draft)
            except Exception as e:  # noqa
                errors = [f"could not build the task's skill copy: {e}"]
        if not errors:
            errors = static_check(draft)
        if not errors:
            err = sandbox_boot_world(draft)
            errors = [err] if err else []
        ledger.write(stage="static", attempt=attempt, errors=errors)
        if not errors:
            result.update(status="passed_static", draft=str(draft))
            break
        messages += [{"role": "assistant", "content": reply.text},
                     {"role": "user", "content": "The draft fails these checks. Fix every one and return the complete "
                                                 "bundle again:\n- " + "\n- ".join(errors)}]
    if gates and result["status"] == "passed_static":
        r = subprocess.run([str(ROOT / ".venv/bin/python"), str(ROOT / "scripts/gate_task.py"), result["draft"]],
                           capture_output=True, text=True, timeout=7200)
        ledger.write(stage="gates", output=r.stdout[-4000:])
        result["status"] = "gated" if r.returncode == 0 else "failed_gates"
    (base / "result.json").write_text(json.dumps(result, indent=2))
    return result


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--model", default="z-ai/glm-5.3")
    ap.add_argument("--revisions", type=int, default=2)
    ap.add_argument("--gates", action="store_true")
    ap.add_argument("--plan-only", action="store_true")
    args = ap.parse_args()
    if args.plan_only:
        print(json.dumps(plan(args.seed), indent=2))
        return 0
    print(json.dumps(run(args.seed, args.model, args.revisions, args.gates), indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
