"""The authoring loop: plan a spec, have a model write the task, check it, revise, then gate it.

    uv run python -m fsbench.author --seed 7 [--model z-ai/glm-5.3] [--revisions 2] [--gates]

Each candidate lives in runs/authoring/<id>/ with:
- spec.json
- every prompt's metadata and token usage (log.jsonl)
- each draft (draft-N/)
- the static-check results

Model-written code never runs on the host: build_world.py runs in a throwaway container with no
network. Harbor gates (--gates) run through scripts/gate_task.py.
"""

import argparse
import json
import random
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path

import yaml

from .bundle import BundleError, materialise, parse, render
from .checks import static_check
from .drift import CATALOGUE
from .llm import Client, LLMError
from . import hard_suite

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs" / "authoring"
EXEMPLARS = ["ship-checkout-v2", "stop-double-charges"]
GENERATED_MARK = "Generated by build_world.py"
SANDBOX_IMAGE = "fullstack-bench/simcloud:dev"

AREAS = ["ship-to-prod (CI/deploy/promotion)", "cloud IaC and identity (simcloud.yaml stacks, policies, federation)",
         "platform delivery (services, traffic splits, rollbacks)", "data (Postgres migrations, backfills, repair)",
         "app auth (Passkeep OIDC sessions, tokens)", "payments and webhooks (Tillpoint)",
         "async processing (queues, idempotent consumers, DLQs)", "observability-driven incident response",
         "refactoring a live service without behaviour change", "secrets and credential rotation"]
DOMAINS = ["online marketplace", "B2B invoicing", "food delivery", "ticketing", "subscription SaaS billing",
           "logistics tracking", "fitness bookings", "travel itineraries", "creator payouts", "inventory for retail"]
VENDORS = {"tillpoint": "payments", "passkeep": "identity"}


def plan(seed: int) -> dict:
    rng = random.Random(seed)
    weird = yaml.safe_load((ROOT / "fsbench" / "weirdness.yaml").read_text())
    areas = rng.sample(AREAS, 3)
    implied = {"tillpoint" for a in areas if "Tillpoint" in a} | {"passkeep" for a in areas if "Passkeep" in a}
    vendors = sorted(implied | {v for v in VENDORS if rng.random() < 0.3})
    drifts = rng.sample(sorted(CATALOGUE), rng.choice([0, 1, 2])) if rng.random() < 0.5 else []
    return {"seed": seed, "primary_area": areas[0], "secondary_areas": areas[1:], "domain": rng.choice(DOMAINS),
            "weirdness": rng.choice(weird), "vendors": vendors, "drifts": drifts,
            "steps_min": 6, "layers_min": 3}


def _skill(name: str) -> str:
    return (ROOT / "skills" / name / "SKILL.md").read_text()


def _exemplar(name: str) -> str:
    task = ROOT / "tasks" / name
    text = render(task, include=("task.toml", "instruction.md", "build_world.py", "environment", "solution", "tests",
                                 "wrong_solutions"))
    # Leave out generated files (the generator itself is included) to keep the prompt small.
    files = parse(text)
    kept = {p: c for p, c in files.items() if GENERATED_MARK not in c[:200]}
    return "".join(f"=== FILE: {p} ===\n{c}" for p, c in kept.items()) + "=== END ===\n"


def system_prompt(spec: dict) -> str:
    drift_text = "\n".join(f"- {d}: the drifted docs claim \"{CATALOGUE[d].wrong}\"; truth is discoverable via "
                           f"{'; '.join(CATALOGUE[d].truth_sources)}" for d in spec["drifts"]) or "- none"
    parts = [
        (ROOT / "fsbench" / "guide.md").read_text(),
        "# Platform skill: SimCloud\n" + _skill("simcloud"),
        *[f"# Vendor skill: {v}\n" + _skill(v) for v in spec["vendors"]],
        "# Docs drift to apply in this task (list these ids in tests/drift_manifest.json as [{\"id\": ...}])\n"
        + drift_text,
        "# Exemplar task 1 (complete; generated files omitted)\n" + _exemplar(EXEMPLARS[0]),
        "# Exemplar task 2 (complete; generated files omitted)\n" + _exemplar(EXEMPLARS[1]),
    ]
    return "\n\n".join(parts)


def task_prompt(spec: dict) -> str:
    w = spec["weirdness"]
    vend = ", ".join(f"{v} ({VENDORS[v]})" for v in spec["vendors"]) or "none (SimCloud only)"
    text = (f"Write a new task.\n\n- Domain: {spec['domain']}\n- Primary area: {spec['primary_area']}\n"
            f"- Also involve: {', '.join(spec['secondary_areas'])}\n- Vendors available: {vend}\n"
            f"- Weird mechanism to make real: {w['id']}: {w['mechanism']} (signals: {', '.join(w['signals'])})\n"
            f"- At least {spec['steps_min']} dependent steps across at least {spec['layers_min']} layers.\n"
            "- It must be original: not a reskin of the exemplars.\n\n"
            "Return the complete bundle (every required file) and nothing after === END ===.")
    if "hard_case" in spec:
        text += "\n\n" + hard_suite.prompt(spec["hard_case"])
        text += f"\nActual author_model: {spec.get('author_model', 'not assigned in plan-only mode')}; author_seed: {spec['seed']}.\n"
    return text


def sandbox_build_world(task: Path, timeout: int = 180) -> str | None:
    """Run the candidate's build_world.py in a container with no network. Returns an error or None."""
    if not (task / "build_world.py").exists():
        return None
    import os
    cmd = ["docker", "run", "--rm", "--network", "none", "--memory", "1g", "--cpus", "1", "--user",
           f"{os.getuid()}:{os.getgid()}", "-v", f"{task}:/task", "-w", "/task", "--entrypoint", "python",
           SANDBOX_IMAGE, "build_world.py"]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return f"build_world.py did not finish within {timeout}s"
    if r.returncode:
        return f"build_world.py failed:\n{(r.stderr or r.stdout)[-1500:]}"
    return None


def build_skills(task: Path) -> None:
    sys.path.insert(0, str(ROOT / "scripts"))
    import build_task_skills
    build_task_skills.build(task)


class Ledger:
    def __init__(self, path: Path):
        self.path = path

    def write(self, **rec) -> None:
        with self.path.open("a") as f:
            f.write(json.dumps({"ts": round(time.time(), 1), **rec}) + "\n")


def model_family(model: str) -> str:
    """Known rotation families; unknown identifiers cannot establish independence."""
    name = model.lower()
    for prefix, family in (("z-ai/glm-", "glm"), ("nvidia/nemotron-", "nemotron"),
                           ("moonshotai/kimi-", "kimi"), ("deepseek-ai/deepseek-", "deepseek")):
        if name.startswith(prefix):
            return family
    raise ValueError("model family is not in the documented NVIDIA rotation")


def review_candidate(client: Client, task: Path, spec: dict, model: str) -> tuple[dict, object]:
    """Independent task QA, never a solver reward judge."""
    design = hard_suite.prompt(spec["hard_case"])
    bundle = render(task, include=("task.toml", "instruction.md", "build_world.py", "environment", "solution", "tests", "wrong_solutions"))
    if len(bundle.encode()) > 512_000:
        raise LLMError("candidate exceeds the bounded QA input size")
    reply = client.chat(model, [
        {"role": "system", "content": "Review a task design, not a solver answer. Check solvability, fair stated conditions, "
         "real cross-layer execution, meaningful performance samples, fault barriers, negative controls rejecting "
         "their specific invariant, and absence of solution leakage. Reject mocked evidence or omitted stages. "
         "Return JSON only: {\"ok\": boolean, \"findings\": [string]}. An ok verdict requires no findings. "
         "Static checks and QA do not qualify a task; runtime gates and human review remain mandatory."},
        {"role": "user", "content": design + "\n\nActual candidate bundle:\n" + bundle},
    ], max_tokens=4000, temperature=0, attempts=1)
    try:
        verdict = json.loads(reply.text)
        if (type(verdict.get("ok")) is not bool or not isinstance(verdict.get("findings"), list)
                or any(not isinstance(v, str) for v in verdict["findings"])
                or verdict["ok"] != (not verdict["findings"])):
            raise ValueError("inconsistent QA result")
    except (ValueError, AttributeError) as error:
        raise LLMError("QA returned a malformed verdict") from error
    return verdict, reply


def run(seed: int, model: str, revisions: int, gates: bool, cand_id: str | None = None,
        hard_case_id: str | None = None, qa_model: str = "nvidia/nemotron-3-ultra-550b-a55b") -> dict:
    if revisions < 0 or (hard_case_id and revisions > 2):
        raise ValueError("curated runs allow zero to two revisions")
    if hard_case_id and model_family(model) == model_family(qa_model):
        raise ValueError("hard-case QA must use a different model family")
    cand_id = cand_id or f"c{seed}-{uuid.uuid4().hex[:6]}"
    base = RUNS / cand_id
    base.mkdir(parents=True, exist_ok=True)
    ledger = Ledger(base / "log.jsonl")
    spec = hard_suite.plan(hard_case_id, seed) if hard_case_id else plan(seed)
    spec["author_model"] = model
    (base / "spec.json").write_text(json.dumps(spec, indent=2))
    result = {"candidate": cand_id, "spec": spec, "status": "failed_static", "author_model": model}
    try:
        client = Client(timeout=60, max_seconds=600) if hard_case_id else Client()
    except LLMError as error:
        result.update(status="llm_error", error=str(error))
        (base / "result.json").write_text(json.dumps(result, indent=2))
        return result
    if hard_case_id and shutil.which("docker") is None:
        result.update(status="environment_unavailable", error="Docker is required for sandboxed world generation; no model call was made")
        (base / "result.json").write_text(json.dumps(result, indent=2))
        return result
    sysmsg = system_prompt(spec)
    messages = [{"role": "system", "content": sysmsg}, {"role": "user", "content": task_prompt(spec)}]
    for attempt in range(revisions + 1):
        try:
            if hard_case_id and sum(len(m["content"].encode()) for m in messages) > 512_000:
                raise LLMError("revision exceeds the bounded author input size")
            reply = client.chat(model, messages, max_tokens=32000 if hard_case_id else 48000,
                                temperature=0.6, attempts=1 if hard_case_id else 3)
        except LLMError as e:
            # Infrastructure, not a quality verdict on the task: record it and stop this candidate.
            ledger.write(stage="author", attempt=attempt, model=model, outcome="llm_error", error=str(e)[:500])
            result.update(status="llm_error", error=str(e)[:500])
            break
        ledger.write(stage="author", attempt=attempt, model=model, prompt_tokens=reply.prompt_tokens,
                     completion_tokens=reply.completion_tokens, seconds=reply.seconds, finish=reply.finish_reason)
        draft = base / f"draft-{attempt}"
        if draft.exists():
            shutil.rmtree(draft)
        try:
            files = parse(reply.text)
            materialise(files, draft)
            errors = []
        except BundleError as e:
            errors = [f"the reply is not a valid bundle: {e}"]
        if not errors:
            err = sandbox_build_world(draft)
            errors = [err] if err else []
        if not errors:
            try:
                build_skills(draft)
            except Exception as e:  # noqa
                errors = [f"could not build the task's skill copy: {e}"]
        if not errors:
            errors = static_check(draft)
        if not errors and hard_case_id:
            errors = hard_suite.candidate_errors(draft, spec["hard_case"], model, seed)
        ledger.write(stage="static", attempt=attempt, errors=errors)
        if not errors and hard_case_id:
            try:
                verdict, qa_reply = review_candidate(client, draft, spec, qa_model)
            except LLMError as error:
                ledger.write(stage="qa", attempt=attempt, model=qa_model, outcome="llm_error", error=str(error)[:500])
                result.update(status="qa_error", error=str(error)[:500])
                break
            ledger.write(stage="qa", attempt=attempt, model=qa_model, verdict=verdict,
                         prompt_tokens=qa_reply.prompt_tokens, completion_tokens=qa_reply.completion_tokens,
                         seconds=qa_reply.seconds)
            result["qa_model"] = qa_model
            errors = verdict["findings"]
            if errors:
                result["status"] = "failed_qa"
            if (draft / "BUILD_NOTES.md").exists():
                errors = [*errors, "BUILD_NOTES.md records unresolved runtime work; keep this candidate under construction"]
                result["status"] = "under_construction"
        if not errors:
            result.update(status="passed_static", draft=str(draft))
            break
        messages += [{"role": "assistant", "content": reply.text},
                     {"role": "user", "content": "The draft fails these checks. Fix every one and return the complete "
                                                 "bundle again:\n- " + "\n- ".join(errors)}]
    if gates and result["status"] == "passed_static":
        r = subprocess.run([str(ROOT / ".venv/bin/python"), str(ROOT / "scripts/gate_task.py"), result["draft"]],
                           capture_output=True, text=True, timeout=7200)
        ledger.write(stage="gates", output=r.stdout[-4000:])
        result["status"] = "gated" if r.returncode == 0 else "failed_gates"
    (base / "result.json").write_text(json.dumps(result, indent=2))
    return result


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--model", default="z-ai/glm-5.3")
    ap.add_argument("--revisions", type=int, default=2)
    ap.add_argument("--gates", action="store_true")
    ap.add_argument("--plan-only", action="store_true")
    ap.add_argument("--hard-case", help="curated full-stack case id (operator-only design input)")
    ap.add_argument("--qa-model", default="nvidia/nemotron-3-ultra-550b-a55b")
    ap.add_argument("--list-hard-cases", action="store_true")
    args = ap.parse_args()
    if args.revisions < 0 or (args.hard_case and args.revisions > 2):
        ap.error("revisions must be nonnegative; curated runs allow at most two revisions")
    if args.list_hard_cases:
        for case in hard_suite.load_cases():
            print(f"{case['id']}: {', '.join(case['work'])} ({case['repair_scope']})")
        return 0
    if args.hard_case:
        try:
            hard_suite.get_case(args.hard_case)
            if model_family(args.model) == model_family(args.qa_model):
                ap.error("hard-case QA must use a different model family")
        except ValueError as error:
            ap.error(str(error))
    if args.plan_only:
        print(json.dumps(hard_suite.plan(args.hard_case, args.seed) if args.hard_case else plan(args.seed), indent=2))
        return 0
    result = run(args.seed, args.model, args.revisions, args.gates,
                 hard_case_id=args.hard_case, qa_model=args.qa_model)
    print(json.dumps(result, indent=2))
    return 0 if result["status"] in {"passed_static", "gated"} else 1


if __name__ == "__main__":
    sys.exit(main())
